services:
  tntn_quiz_octane:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      args:
        VITE_REVERB_APP_KEY: ${VITE_REVERB_APP_KEY:-}
        VITE_REVERB_HOST: ${VITE_REVERB_HOST:-}
        VITE_REVERB_PORT: ${VITE_REVERB_PORT:-}
        VITE_REVERB_SCHEME: ${VITE_REVERB_SCHEME:-}
