[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:octane]
command=%(ENV_SUPERVISOR_OCTANE_COMMAND)s
user=%(ENV_SUPERVISOR_OCTANE_USER)s
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue]
command=%(ENV_SUPERVISOR_QUEUE_COMMAND)s
user=%(ENV_SUPERVISOR_QUEUE_USER)s
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:schedule]
command=%(ENV_SUPERVISOR_SCHEDULE_COMMAND)s
user=%(ENV_SUPERVISOR_SCHEDULE_USER)s
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
command=%(ENV_SUPERVISOR_REVERB_COMMAND)s
user=%(ENV_SUPERVISOR_REVERB_USER)s
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
